insert into 
  TEILE_SLGEL
(
PROJEKT_NO,
HPOS,
SPOS,
LFD_NO,
LAUFNR,
LFD_NO_PROJ_POS,
KANTE_V_ST,
KANTE_H_ST,
KANTE_L_ST,
KANTE_R_ST,
KANTE_V_VN,
KANTE_H_VN,
KANTE_L_VN,
KANTE_R_VN,
STAERKE,
KANTE_V_B,
KANTE_H_B,
KANTE_L_B,
KANTE_R_B,
BEZEICHNUNG,
BESCHREIBUNG,
MATERIAL,
LAENGE,
BREITE,
BELAG_A,
BELAG_I,
KANTE_V, 
KANTE_H,
KANTE_L,
KANTE_R,
KANTE_V_L,
KANTE_H_L,
KANTE_L_L,
KANTE_R_L,
LO,
MO,
RO,
MR,
RU,
MU,
LU,
ML,
MENGE,
KR_SAUM,
KL_SAUM,
KH_SAUM,
KV_SAUM,
BK_NO
)

VALUES
(
	'TEST_10',
	888,
	888,
	888,
	1,
	1,
	19,
	19,
	19,
	19,
	'N',
	'N',
	'N',
	'N',
	19,
	19,
	19,
	19,
	19,
	'Platte1',
	'1048',
	'SP19',
	800,
	400,
	'FUAH',
	'FUBU',
	'ABS85',
	'ABS85',
	'ABS85',
	'ABS85',
	800,
	400,
	800,
	400,
	6,
	3,
	6,
	3,
	6,
	3,
	6,
	3,
	1,
	0,
	0,
	0,
	0,
	'LEER'
)

insert into PROJ_POS_BESCHR (PROJEKT_NO, HPOS, SPOS, BESCHREIBUNG) VALUES ('TEST_10', 888, 888, 'POSITION888');
insert into PTTECH_POS (PROJEKT_NO, HPOS, SPOS, LFD_NO, MENGE, BK_NO) VALUES ('TEST_10', 888, 888, 888, 1, 'LEER')

manuelle zuweisung
PROJEKT_NO
HPOS [int]

hierarchie information (aus imos)
SPOS = laufende nummer, jeweils gleich fuer alle die gleiche IDBGPRS.HIGHARTID

generieren:
LFD_NO (beginned von der letzten+1 im bestehenden protime projekt)
LAUFNR (beginned von der letzten+1 im bestehenden protime projekt)
LFD_NO_PROJ_POS = (beginned von der letzten+1 im bestehenden protime projekt)

uebernehmen von ARTIKEL aus protime [KEY = KANTE_V/H/L/R | artikel_bez
KANTE_V_ST = ARTIKEL.MATERIALSTAERKE where KANTE_V = ARTIKEL.ARTIKEL_NO 
KANTE_H_ST = ARTIKEL.MATERIALSTAERKE where KANTE_H = ARTIKEL.ARTIKEL_NO
KANTE_L_ST = ARTIKEL.MATERIALSTAERKE where KANTE_L = ARTIKEL.ARTIKEL_NO
KANTE_R_ST = ARTIKEL.MATERIALSTAERKE where KANTE_R = ARTIKEL.ARTIKEL_NO
KANTE_V_VN = KANTE_VN where KANTE_V = ARTIKEL.ARTIKEL_NO
KANTE_H_VN = KANTE_VN where KANTE_H = ARTIKEL.ARTIKEL_NO
KANTE_L_VN = KANTE_VN where KANTE_L = ARTIKEL.ARTIKEL_NO
KANTE_R_VN = KANTE_VN where KANTE_R = ARTIKEL.ARTIKEL_NO
STAERKE = ARTIKEL.MATERIALSTAERKE where MATERIAL = ARTIKEL.ARTIKEL_NO
KANTE_V_B = ARTIKEL.MATERIALSTAERKE where MATERIAL = ARTIKEL.ARTIKEL_NO
KANTE_H_B = ARTIKEL.MATERIALSTAERKE where MATERIAL = ARTIKEL.ARTIKEL_NO
KANTE_L_B = ARTIKEL.MATERIALSTAERKE where MATERIAL = ARTIKEL.ARTIKEL_NO
KANTE_R_B = ARTIKEL.MATERIALSTAERKE where MATERIAL = ARTIKEL.ARTIKEL_NO

uebernehmen aus IMOS:
BEZEICHNUNG = IDBGPL.NAME1
BESCHREIBUNG = IDBGPL.BARCODE
MATERIAL = IDBGPL.MATID
LAENGE = IDBGPL.FLENG
BREITE = IDBGPL.FWIDTH
BELAG_A = IDBGPL.SURFTID
BELAG_I = IDBGPL.SURFBID
  [1=V, 2=R, 3=H, 4=L]
KANTE_V = IDBPRF.PRFID  
KANTE_H = IDBPRF.PRFID
KANTE_L = IDBPRF.PRFID
KANTE_R = IDBPRF.PRFID
KANTE_V_L = IDBPRF.PRFLEN
KANTE_H_L = IDBPRF.PRFLEN
KANTE_L_L = IDBPRF.PRFLEN
KANTE_R_L = IDBPRF.PRFLEN
LO = 6
MO = 3
RO = 6
MR = 3
RU = 6
MU = 3
LU = 6
ML = 3
MENGE = IDBGPL.CNT

0:
KR_SAUM
KL_SAUM
KH_SAUM
KV_SAUM

BK_NO = 'LEER'

null:
TEIL_NO
OBERFL_A
OBERFL_I
KANTE_V_BEH
KANTE_H_BEH
KANTE_L_BEH
KANTE_R_BEH
KANTE_V_PROFIL
KANTE_H_PROFIL
KANTE_L_PROFIL
KANTE_R_PROFIL
VAR1
VAR2
VAR3
VAR4
VAR5
VAR6
VAR7
VAR8
VAR9
VAR10
VAR11
VAR12
VAR13
VAR14
VAR15
VAR16
VAR17
VAR18
VAR19
VAR20
VAR21
VAR22
VAR23
VAR24
VAR25
VAR26
VAR27
VAR28
VAR29
VAR30
ADM_INS_USER
ADM_UPD_USER
ADM_INS_DATE
ADM_UPD_DATE
SURROGAT
TM_RM_L
TM_RM_B
TM_RM_ST
TM_FM_L
TM_FM_B
TM_FM_ST
OA_RM_L
OA_RM_B
OA_RM_ST
OI_RM_L
OI_RM_B
OI_RM_ST
BA_RM_L
BA_RM_B
BA_RM_ST
BI_RM_L
BI_RM_B
BI_RM_ST
BA_FM_L
BA_FM_B
BA_FM_ST
BI_FM_L
BI_FM_B
BI_FM_ST
KV_RM_L
KV_RM_B
KV_RM_ST
KH_RM_L
KH_RM_B
KH_RM_ST
KL_RM_L
KL_RM_B
KL_RM_ST
KR_RM_L
KR_RM_B
KR_RM_ST
_MENGE
FIX_LAENGE
NC_BEZ0
NC_BEZ1
NC_BEZ10
NC_BEZ11
NC_BEZ12
NC_BEZ13
NC_BEZ14
NC_BEZ15
NC_BEZ16
NC_BEZ17
NC_BEZ18
NC_BEZ19
NC_BEZ2
NC_BEZ20
NC_BEZ3
NC_BEZ4
NC_BEZ5
NC_BEZ6
NC_BEZ7
NC_BEZ8
NC_BEZ9
NC_PROG0
NC_PROG1
NC_PROG10
NC_PROG11
NC_PROG12
NC_PROG13
NC_PROG14
NC_PROG15
NC_PROG16
NC_PROG17
NC_PROG18
NC_PROG19
NC_PROG2
NC_PROG20
NC_PROG3
NC_PROG4
NC_PROG5
NC_PROG6
NC_PROG7
NC_PROG8
NC_PROG9
NC_VAR_NO0
NC_VAR_NO1
NC_VAR_NO10
NC_VAR_NO11
NC_VAR_NO12
NC_VAR_NO13
NC_VAR_NO14
NC_VAR_NO15
NC_VAR_NO16
NC_VAR_NO17
NC_VAR_NO18
NC_VAR_NO19
NC_VAR_NO2
NC_VAR_NO20
NC_VAR_NO3
NC_VAR_NO4
NC_VAR_NO5
NC_VAR_NO6
NC_VAR_NO7
NC_VAR_NO8
NC_VAR_NO9
VERSCHNITT
FIX_BREITE
FIX_STAERKE
FIX_KANTE_VL
FIX_KANTE_HL
FIX_KANTE_LL
FIX_KANTE_RL
LAENGE_FORMAT
BREITE_FORMAT
BEHANDLUNG_I
BEHANDLUNG_A
